import 'package:eshopplus_seller/core/configs/appConfig.dart';

Map<String, String> defaultLanguageTranslatedValues = {
  "skip": "Skip",
  "sign_in": "Sign In",
  "sign_up": "Sign Up",
  "login": "Login",
  "hi_welcome_back": "Hi, Welcome Back!",
  "please_enter_your_login_details_below_to_start_using_app":
      "Please enter your login details below to start using app.",
  "mobile_number": "Mobile Number",
  "we_will_send_a_password_reset_link_to_your_registered_email_id":
      "We will send a password reset link to your registered email ID.",
  "dont_have_an_account": "Don't have an account?",
  "please_enter_valid_mobile_number": "Please enter valid mobile number",
  "password": "Password",
  "forgot_password": "Forgot Password?",
  "get_password": "Get Password",
  "enter_verification_code": "Enter Verification Code",
  "we_have_sent_a_verification_code_to": "We have sent a verification code to",
  "verify_otp": "Verify OTP",
  "didnt_get_the_code": "Didn't get the code?",
  "resend_otp": "Resend OTP",
  "reset_password": "Reset password",
  "new_password": "New password",
  "confirm_new_password": "Confirm New Password",
  "please_type_something_youll_remember":
      "Please Type something you'll remember",
  "seller_registration": "Seller Registration",
  "next": "Next",
  "back": "Back",
  "register": "Register",
  "personal_details": "Personal Details",
  "confirm_password": "Confirm Password",
  "name": "Name",
  "email": "Email",
  "address": "Address",
  "store_details": "Store Details",
  "select_store": "Select Store",
  "grocery_store_info": "Grocery Store Info",
  "store_name": "Store Name",
  "store_url": "Store URL",
  "store_description": "Store Description",
  "bank_details": "Bank Details",
  "other_details": "Other Details",
  "account_name": "Account Name",
  "account_number": "Account Number",
  "bank_name": "Bank Name",
  "bank_code": "Bank Code",
  "tax_name": "TAX Name",
  "tax_number": "TAX Number",
  "pan_number": "PAN Number",
  "latitude": "Latitude",
  "longitude": "Longitude",
  "address_proof": "Address Proof",
  "authorized_signature": "Authorized Signature",
  "national_identity_card": "National Identity Card",
  "store_logo": "Store Logo",
  "store_thumbnail": "Store Thumbnail",
  "my_profile": "My Profile",
  "home": "Home",
  "orders": "Orders",
  "products": "Products",
  "user": "User",
  "account": "Account",
  "settings": "Settings",
  "support_&_information": "Support & Information",
  "more": "More",
  "manage_pickup_location": "Manage Pickup Location",
  "stock_management": "Stock Management",
  "sales_report": "Sales Report",
  "change_language": "Change Language",
  "faqs": "FAQ's",
  "contact_us": "Contact us",
  "about_us": "About us",
  "terms_and_policies": "Terms and Policies",
  "rate_us": "Rate Us",
  "logout": "Logout",
  "delete_account": "Delete Account",
  "edit_profile": "Edit profile",
  "wallet": "Wallet",
  "chat": "Chat",
  "add_product": "Add Product",
  "add_new_product": "Add New Product",
  "edit_product": "Edit Product",
  "add_combo": "Add Combo",
  "edit_combo": "Edit Combo",
  "change_password": "Change Password",
  "notifications_preference": "Notifications Preference",
  "current_password": "Current Password",
  "enter_your_current_password": "Enter your current password",
  "enter_your_new_password": "Enter your new password",
  "are_you_sure_you_want_to_logout": "Are you sure you want to logout?",
  "yes_logout": "Yes, Logout",
  "stay_logged_in": "Stay logged in",
  "are_you_sure_you_want_to_delete_your_account":
      "Are you sure you want to delete your account?",
  "yes_delete": "Yes, Delete",
  "keep_account": "Keep account",
  "notifications": "Notifications",
  "push_notifications": "Push Notifications",
  "promotional_emails": "Promotional Emails",
  "promotional_sms": "Promotional SMS",
  "save_password": "Save Password",
  "delete_my_account_now": "Delete My Account Now",
  "back_to_settings": "Back to Settings",
  "please_note_that_this_action_is_irreversible_and_will_permanently_remove_your_account_information":
      "Please note that this action is irreversible and will permanently remove your account information.",
  "by_deleting_your_account_youll_lose_access_to_your_order_history_and_personalized_settings_if_you_have_any_queries_dont_hesitate_to_contact_us":
      "By deleting your account, you'll lose access to your order history and personalized settings. If you have any queries, don't hesitate to contact us.",
  "something_went_wrong_please_try_again_later":
      "Something went wrong.Please try again later!",
  "no": "No",
  "yes": "Yes",
  "terms_&_conditions": "Terms & Conditions",
  "privacy_policy": "Privacy Policy",
  "shipping_policy": "Shipping Policy",
  "return_and_refund_policy": "Return and Refund Policy",
  "seller_terms_and_conditions": "Seller Terms and Conditions",
  "seller_privacy_policy": "Seller Privacy Policy",
  "are_you_sure": "Are you sure?",

  "exit": "Exit",
  "submit": "Submit",
  "product_name": "Product Name",
  "product_type": "Product Type",
  "brand": "Brand",
  "tags": "Tags",
  "select_category": "Select Category",
  "indicator": "Indicator",
  "made_in": "Made In",
  "hsn_code": "HSN Code",
  "warranty_period": "Warranty Period",
  "guarantee_period": "Guarantee Period",
  "product_short_description": "Product Short Description",
  "product_tax": "Product Tax",
  "tax_include_in_price": "Tax Include In Price",
  "select_indicator": "Select Indicator",
  "total_allowed_quantity": "Total Allowed Quantity",
  "minimum_order_quantity": "Minimum Order Quantity",
  "deliverable_type": "Deliverable Type",
  "select_deliverable_type": "Select Deliverable Type",
  "selected_category": "Selected Category",
  "select_zipcode": "Select ZipCode",
  "for_standard_shipping": "For Standard Shipping",
  "cancelable_till_which_status": "Cancelable Till Which Status?",
  "main_image": "Main Image",
  "other_images": "Other Images",
  "description": "Description",
  "extra_description": "Extra Description",
  "general_information": "General Information",
  "type_of_product": "Type Of Product",
  "save_settings": "Save Settings",
  "attributes": "Attributes",
  "variations": "Variations",
  "simple_product": "Simple Product",
  "variable_product": "Variable Product",
  "digital_product": "Digital Product",
  "special_price": "Special Price",
  "price": "Price",
  "selling_price": "Selling Price",
  "weight_kg": "Weight (kg)",
  "height_cms": "Height (cms)",
  "breadth_cms": "Breadth (cms)",
  "length_cms": "Length (cms)",
  "enable_stock_management": "Enable Stock Management",
  "in_stock": "In Stock",
  "out_of_stock": "Out Of Stock",
  "low_in_stock": "Low in Stock",
  "stock_status": "Stock Status",
  "select_type": "Select Type",
  "total_stock": "Total Stock",
  "sku": "SKU",
  "choose_stock_management_type": "Choose Stock Management Type",
  "video_link": "Video Link",
  "error_in_video_uploading_please_try_again":
      "Error in video uploading please try again...!",
  "vimeo": "Vimeo",
  "youtube": "Youtube",
  "select_other_video_type": "Select Other Video Type",
  "select_video_type": "Select Video Type",
  "paste_vimeo_video_link_url": "Paste Vimeo Video link / url ...!",
  "paste_youtube_video_link_url": "Paste Youtube Video link / url...!",
  "add_attribute": "Add Attribute",
  "save_attribute": "Save Attribute",
  "select_attribute": "Select Attribute",
  "select_attributes": "Select Attributes",
  "add_attributes_value": "Add attributes value",
  "none": "None",
  "veg": "Veg",
  "non_veg": "Non-Veg",
  "received": "Received",
  "waiting": "Waiting",
  "processed": "Processed",
  "shipped": "Shipped",
  "delivered": "Delivered",
  "cancelled": "Cancelled",
  "returned": "Returned",
  "variable_level": "Variable Level",
  "product_level": "Product Level",
  "add_pickup_location": "Add Pickup Location",
  "pickup_location_name": "Pickup Location Name",
  "pickup_location": "Pickup Location",
  "phone_number": "Phone Number",
  "country": "Country",
  "state": "State",
  "city": "City",
  "pincode": "Pincode",
  "additional_address": "Additional Address",
  "add_location": "Add Location",
  "add_faqs": "Add FAQ's",
  "update_profile": "Update Profile",
  "select_product": "Select Product",
  "question": "Question",
  "answer": "Answer",
  "cancel": "Cancel",
  "edit_product_faqs": "Edit Product FAQ's",
  "current_balance": "Current Balance",
  "withdraw_money": "Withdraw Money",
  "wallet_transaction": "Wallet Transaction",
  "wallet_withdraw": "Wallet Withdraw",
  "message": "Message",
  "date": "Date",
  "type": "Type",
  "amount": "Amount",
  "total_orders": "Total Orders",
  "grand_total": "Grand Total",
  "delivery_charge": "Delivery Charge",
  "total": "Total",
  "from_date": "From Date",
  "to_date": "To Date",
  "add": "Add",
  "customer_name": "Customer Name",
  "order_date": "Order Date",
  "discount": "Discount",
  "total_amount": "Total Amount",
  "download_report": "Download Report",
  "current_stock": "Current Stock",
  "quantity": "Quantity",
  "subtract": "Subtract",
  "fail": "Fail",
  "success": "Success",
  "pending": "Pending",
  "update_stock": "Update Stock",
  "update": "Update",
  "search_all_products": "Search all Products",
  "approved": "Approved",
  "rejected": "Rejected",
  "deactive": "Deactive",
  "combo_products": "Combo Products",
  "product_details": "Product Details",
  "reviews": "Reviews",
  "product_faqs": "Product FAQ's",
  "product_status": "Product Status",
  "edit": "Edit",
  "delete": "Delete",
  "add_product_faq": "Add Product FAQ",
  "all": "All",
  "simple": "Simple",
  "digital": "Digital",
  "physical": "Physical",
  "variable": "Variable",
  "combo": "Combo",
  "sold_out": "Sold Out",
  "clear_filters": "Clear Filters",
  "apply": "Apply",
  "sort_by": "Sort By",
  "top_rated": "Top Rated",
  "newest_first": "Newest First",
  "oldest_first": "Oldest First",
  "price_low_to_high": "Price Low to High",
  "price_high_to_low": "Price High to Low",
  "customer_reviews": "Customer Reviews",
  "all_reviews": "All Reviews",
  "search_all_orders": "Search all orders",
  "status": "Status",
  "order_filter": "Order Filter",
  "payment_mode": "Payment Mode",
  "order_details": "Order Details",
  "order_date_time": "Order Date/Time",
  "order_id": "Order ID",
  "parcel_id": "Parcel ID",
  "payment_method": "Payment Method",
  "order_status": "Order Status",
  "select_status": "Select Status",
  "choose_delivery_boy": "Choose Delivery Boy",
  "add_order_tracking": "Add Order Tracking",
  "deliver_by": "Deliver By",
  "order_tracking": "Order Tracking",
  "courier_agency": "Courier Agency",
  "tracking_id": "Tracking ID",
  "url": "URL",
  "reset": "Reset",
  "save": "Save",
  "download_invoice": "Download Invoice",
  "create_shiprocket_order": "Create Shiprocket Order",
  "create_shiprocket_order_parcel": "Create Shiprocket Order Parcel",
  "total_weight_of_box": "Total Weight Of Box",
  "create_order": "Create Order",
  "note": "Note",
  "make_your_pickup_location_associated_with_the_order_is_verified_from_the_shiprocket_dashboard_and_then_in_the_admin_panel_if_it_is_not_verified_you_will_not_be_able_to_generate_awb_later":
      "Make your pickup location associated with the order is verified from the Shiprocket Dashboard and then in the admin panel. If it is not verified you will not be able to generate AWB later.",
  "shipping_details": "Shipping Details",
  "delivery_preference": "Delivery Preference",
  "price_details": "Price Details",
  "subtotal": "Subtotal",
  "shipping_charges": "Shipping Charges",
  "wallet_balance": "Wallet Balance",
  "discount_amount": "Discount Amount",
  "no_internet_connection_please_try_again":
      "No Internet Connection. Please try again",
  "incorrect_otp": "Incorrect otp",
  "retry": "Retry",
  "profile": "Profile",
  "internal_server_error_please_try_again_later":
      "Internal Server Error. Please try again later!",
  "data_not_available": "Data not available",
  "please_enter_valid_email_address": "Please enter valid email address",
  "please_enter_email": "Please enter email",
  "please_enter_some_text": "Please enter some text",
  "please_enter_name": "Please Enter Name",
  "enter_confirmation_password": "Enter Confirmation Password",
  "confirmation_password_not_matched": "Confirmation Password not Matched",
  "upload_address_proof_file": "Upload Address Proof file",
  "upload_authorized_signature_file": "Upload Authorized Signature file",
  "upload_nationalid_card_file": "Upload NationalId Card file",
  "please_enter_url": "Please enter url",
  "please_enter_valid_url": "Please enter valid url",
  "upload_store_thumbnail": "Upload Store Thumbnail",
  "upload_store_logo": "Upload Store Logo",
  "try_again": "Try Again",
  "search": "Search",
  "delivery_instruction": "Delivery Instruction",
  "order_created": "Order created",
  "app_language": "App Language",
  "please_enter_some_value": "Please enter some value",
  "verification_failed_please_try_again":
      "Verification failed. Please try again!",
  "email_adddress_is_invalid_pelase_enter_valid_format":
      "Email adddress is invalid. Pelase enter valid format",
  "name_is_invalid_please_enter_valid_format":
      "Name is invalid. Please enter valid format",
  "otp_is_incorrect": "OTP is incorrect",
  "password_mismatch_message":
      'Confirm Password do not match with new password',
  "please_login_to_continue": "Please login to continue",
  "require_recent_login_error_message":
      'The user must relogin before this operation can be executed.\nThen you can initiate delete procedure.',
  "require_recent_login": 'Require Recent Login',
  "deactivated_error_message": 'You are deactivated. You can\'t login to app.',
  "the_password_must_be_at_least_6_characters":
      "The password must be at least 6 characters.",
  "sorry_for_the_inconvenience_this_app_is_under_maintenance":
      "Sorry for the inconvenience. This app is under maintenance.",
  "send": 'Send',
  "withdrawal_amount": 'Withdrawal Amount',
  "ifsc_code": "IFSC Code",
  "select_date": "Select Date",
  "to_date_not_before_from_date": "To Date not before From Date",
  "physical_product": "Physical Product",
  "quantity_step_size": "Quantity Step Size",
  "exclude": "Exclude",
  "include": "Include",
  "has_similar_products": "Has similar products?",
  "minimum_free_delivery_order_quantity":
      "Minimum Free Delivery Order Quantity",
  "delivery_charges": "Delivery Charges",
  "is_cod_allowed": "IS COD Allowed?",
  "is_returnable": "IS Returnable?",
  "is_cancelable": "IS Cancelable?",
  "select_city": "Select City",
  "shop": "Shop",
  "top_rated_product": "Top Rated Product",
  "country_of_origin": "Country of Origin",
  "filter_review": "Filter Review",
  "this_product_has_no_ratings_or_reviews_yet":
      "This product has no ratings or reviews yet.",
  "are_you_sure_you_want_to_delete_this_product":
      "Are you sure you want to delete this product?",
  "new": "New",
  "earlier": "Earlier",
  "write_message": "Write message",
  "download": "Download",
  "storage_permission_not_granted": "Storage permission not granted",
  "update_required": "Update Required",
  "a_new_version_of_this_app_is_available_with_important_improvements_and_features_to_continue_using_the_app_please_update_to_the_latest_version":
      "A new version of this app is available with important improvements and features. To continue using the app, please update to the latest version.",
  "admin": "Admin",
  "users": "Users",
  "enter_price": "Enter Price",
  "enter_special_price": "Enter Special Price",
  "special_price_should_be_less_than_price":
      "Special Price should be less than price",
  "house_no_flat_no_road_no": "House no / Flat no / Road no",
  "sort": "Sort",
  "filter": "Filter",
  "self_hosted": "Self Hosted",
  "is_download_allowed": "Is Download Allowed?",
  "download_link_type": "Download Link Type",
  "add_link": "Add Link",
  "digital_product_link": "Digital Product Link",
  "choose_downloadable_media_for_product":
      "Choose Downloadable Media for Product",
  "select_media": "Select Media",
  "total_balance": "Total Balance",
  "total_sales": "Total Sales",
  "total_products": "Total Products",
  "low_stock": "Low Stock",
  "top_selling_products": "Top Selling Products",
  "most_selling_category": "Most Selling Category",
  "weekly": "Weekly",
  "monthly": "Monthly",
  "yearly": "Yearly",
  "daily": "Daily",
  "today": "Today",
  "sold": "Sold",
  "overview_statistic": "Overview Statistic",
  "upload": "Upload",
  "select_video": "Select Video",
  "select_checkbox_if_the_attribute_is_to_be_used_for_variation":
      "Select checkbox if the attribute is to be used for variation",
  "revenue": "Revenue",
  "sales": "Sales",
  "new_messages": "New Messages",
  "view_all": "View All",
  "customer_support": "Customer Support",
  "withdraw": "Withdraw",
  "are_you_sure_you_wants_to_add_product":
      "Are you sure, you wants to Add Product ?",
  "active": "Active",
  "add_store": "Add Store",
  "please_enter_all_required_fields": "Please enter all required fields",
  "combo_product_list": "Combo Product List",
  "similar_product_list": "Similar Product List",
  "not_found_any_active_store_please_ask_your_admin_to_approve_your_store":
      "Not found any active store. Please ask your admin to approve your store",
  "return_pending": "Return Pending",
  "return_approved": "Return Approved",
  "return_decline": "Return Decline",
  "are_you_sure_you_wants_to_update_product":
      "Are you sure, you wants to Update Product ?",
  "invoice_downloaded_successfully": "Invoice downloaded successfully",
  "file_downloaded_successfully": "File downloaded successfully",
  "view": "View",
  "seller": "Seller",
  "select_similar_products": "Select Similar Products",
  "are_you_sure_you_want_to_turn_off_notifications_from_appname":
      "Are you sure you want to turn off notifications from $appName?",
  "select_zones": "Select Zones",
  "serviceable_zipcodes": "Serviceable Zipcodes",
  "serviceable_cities": "Serviceable Cities",
  "order_items": "Order Items",
  "shipments": "Shipments",
  "all_parcels": "All Parcels",
  "parcel_details": "Parcel Details",
  "create_a_parcel": "Create a Parcel",
  "are_you_sure_you_want_to_delete_this_parcel":
      "Are you sure you want to delete this parcel?",
  "are_you_sure_you_want_to_delete_this_faq":
      "Are you sure you want to delete this FAQ?",
  "items_are_already_shipped": "Items Are Already Shipped.",
  "parcel_title": "Parcel Title",
  "parcel_name": "Parcel Name",
  "payment_type": "Payment Type",
  "order_total": "Order Total",
  "more_products": "More Products",
  "created_on": "Created On",
  "total_items": "Total items",
  "parcel_date_time": "Parcel Date/Time",
  "parcel_management": "Parcel Management",
  "parcel_status": "Parcel Status",
  "parcel_items": "Parcel Items",
  "enter_valid_amount": "Enter Valid Amount",
  "no_zipcode_found": 'No Zipcode Found for selected city',
  "select_product_for_parcel": 'Please select products to add in parcel',
  "select_product_for_status": 'Please select products to update status',
  "modifications_are_not_allowed_in_demo_app":
      "Modifications are not allowed in demo app",
  "is_attachment_required": "Is Attachment Required?",
  "other_documents": "Other Documents",
  "upload_other_documents": "Upload Other Documents",
  "total_commission": "Total Commission",
  "note_city_and_zipcode_are_just_used_for_store_address":
      "Note: City and zipcode are just used for store address",
  "note_product_deliverable_zones_will_be_based_on_the_sellers_serviceable_zones":
      "Note: Product deliverable zones will be based on the seller's serviceable zones.",
  "manage_product_deliverability": "Manage Product Deliverability",
  "changing_this_setting_will_affect_product_deliverability_settings_if_you_modify_this_ensure_that_product_deliverability_settings_are_updated_accordingly_or_it_may_result_in_errors_where_products_are_marked_as_non_deliverable_ndo_you_want_to_update_products_deliverability_settins_now":
      "Changing this setting will affect product deliverability settings. If you modify this, ensure that product deliverability settings are updated accordingly, or it may result in errors where products are marked as non-deliverable.\nDo you want to update product's deliverability settins now?",
  "specific_zones": "Specific Zones",
  "deliverable_zones": "Deliverable Zones",
  "zones": "Zones",
  "it_may_happen_that_category_not_added_to_your_profile_ask_your_admin_to_add_it_first":
      "It may happen that category not added to your profile. Ask your admin to add it first.",
  "item_total": "Item Total",
  "coupon_discount": "Coupon Discount",
  "register_for_new_store": "Register for new store",
  "some_selected_items_cannot_be_included_in_the_parcel_due_to_their_invalid_current_status_such_as_draft_awaiting_cancelled_or_delivered":
      "Some selected items cannot be included in the parcel due to their invalid current status such as draft, awaiting, cancelled or delivered.",
  "open_link": "Open link",
  "add_variant_warning": "Please add at least one variant",
  "add_variant_images": "Please add at least one image for each variant",
  "are_you_sure_you_want_to_exit": "Are you sure you want to exit?",
  "custom_prompt": "Custom Prompt",
  "enter_your_own_AI_prompt_(optional)": "Enter your own AI prompt (optional)",
  "generate_description_with_AI": "Generate description with AI",
  "please_enter_product_name_first": "Please enter product name first",
  "return_pickedup": "Return pickedup",
  "press_back_again_to_exit": "Press back again to Exit",
  "please_enter_custom_prompt_description":
      "Please enter custom prompt Description",
  //new

  "add_category": "Add Category",
  "add_brand": "Add Brand",
  "select_category_for_subCategory": "Select Category for subCategory",
  "image": "Image",
  "banner": "Banner",
  "please_upload_image": "Please upload Image",
  "please_select_status": "Please select status",
  "read_more": "Read More",
  "read_less": "Read Less",
  "insufficient_wallet_balance": "Insufficient wallet balance",
  "update_return_request": "Update Return Request",
  "return_requests": "Return Requests",
  "qty": "Qty",
  "add_remarks": "Add Remarks",
  "remarks": "Remarks",
  "unauthenticated_please_login_again": "Unauthenticated. Please login again."
};
