Map<String, String> defaultLanguageTranslatedValues = {
  "skip": "Skip",
  "sign_in": "Sign In",
  "sign_up": "Sign Up",
  "login": "Login",
  "hi_welcome_back": "Hi, Welcome Back!",
  "please_enter_your_login_details_below_to_start_using_app":
      "Please enter your login details below to start using app.",
  "mobile_number": "Mobile Number",
  "we_will_send_a_password_reset_link_to_your_registered_email_id":
      "We will send a password reset link to your registered email ID.",
  "donot_have_an_account": "Don't have an account?",
  "please_enter_valid_mobile_number": "Please enter valid mobile number",
  "password": "Password",
  "forgot_password": "Forgot Password?",
  "get_password": "Get Password",
  "reset_password": "Reset password",
  "new_password": "New password",
  "confirm_new_password": "Confirm New Password",
  "change_password": "Change Password",
  "notifications_preference": "Notifications Preference",
  "current_password": "Current Password",
  "enter_your_current_password": "Enter your current password",
  "enter_your_new_password": "Enter your new password",
  "are_you_sure_you_want_to_logout?": "Are you sure you want to logout?",
  "yes_logout": "Yes, Logout",
  "stay_logged_in": "Stay logged in",
  "are_you_sure_you_want_to_delete_your_account":
      "Are you sure you want to delete your account?",
  "yes_delete": "Yes, Delete",
  "keep_account": "Keep account",
  "notifications": "Notifications",
  "push_notifications": "Push Notifications",
  "promotional_emails": "Promotional Emails",
  "promotional_sms": "Promotional SMS",
  "save_password": "Save Password",
  "delete_my_account_now": "Delete My Account Now",
  "back_to_settings": "Back to Settings",
  "please_note_that_this_action_is_irreversible_and_will_permanently_remove_your_account_information":
      "Please note that this action is irreversible and will permanently remove your account information.",
  "by_deleting_your_account_you_ll_lose_access_to_your_order_history_and_personalized_settings_if_you_have_any_queries_don_t_hesitate_to_contact_us":
      "By deleting your account, you'll lose access to your order history and personalized settings. If you have any queries, don't hesitate to contact us.",
  "something_went_wrong_please_try_again_later":
      "Something went wrong.Please try again later!",
  "no_data_found": "No data found",
  "no": "No",
  "yes": "Yes",
  "terms_and_conditions": "Terms And Conditions",
  "terms_and_policies": "Terms And Policies",
  "privacy_policy": "Privacy Policy",
  "shipping_policy": "Shipping Policy",
  "return_and_refund_policy": "Return and Refund Policy",
  "are_you_sure": "Are you sure?",
  "are_you_sure_you_want_to_exit_the_app":
      "Are you sure you want to exit the app?",
  "exit": "Exit",
  "submit": "Submit",
  "received": "Received",
  "awaiting": "Awaiting",
  "processed": "Processed",
  "shipped": "Shipped",
  "delivered": "Delivered",
  "cancelled": "Cancelled",
  "returned": "Returned",
  "no_internet_connection_please_try_again":
      "No Internet Connection. Please try again",
  "incorrect_otp": "Incorrect otp",
  "retry": "Retry",
  "profile": "Profile",
  "internal_server_error_please_try_again_later":
      "Internal Server Error. Please try again later!",
  "data_not_available": "Data not available",
  "please_enter_valid_email_address": "Please enter valid email address",
  "please_enter_email": "Please enter email",
  "please_enter_some_text": "Please enter some text",
  "please_enter_name": "Please Enter Name",
  "enter_confirmation_password": "Enter Confirmation Password",
  "confirmation_password_not_matched": "Confirmation Password not Matched",
  "app_language": "App Language",
  "please_enter_some_value": "Please enter some value",
  "the_password_must_be_at_least_6_characters":
      "The password must be at least 6 characters.",
  "sorry_for_the_inconvenience_this_app_is_under_maintenance":
      "Sorry for the inconvenience. This app is under maintenance.",
  "send": 'Send',
  "withdrawal_amount": 'Withdrawal Amount',
  "ifsc_code": "IFSC Code",
  "verification_failed_please_try_again":
      "Verification failed. Please try again!",
  "email_adddress_is_invalid_pelase_enter_valid_format":
      "Email adddress is invalid. Pelase enter valid format",
  "name_is_invalid_please_enter_valid_format":
      "Name is invalid. Please enter valid format",
  "otp_is_incorrect": "OTP is incorrect",
  "password_mismatch_message":
      'Confirm Password do not match with new password',
  "please_login_to_continue": "Please login to continue",
  "require_recent_login_error_message":
      'The user must relogin before this operation can be executed.\nThen you can initiate delete procedure.',
  "require_recent_login": 'Require Recent Login',
  "deactivated_error_message": 'You are deactivated. You can\'t login to app.',
  "home": "Home",
  "my_delivery": "My Delivery",
  "cash": "Cash",
  "user": "User",
  "change_language": "Change Language",
  "contact_us": "Contact us",
  "about_us": "About us",
  "rate_us": "Rate Us",
  "logout": "Logout",
  "delete_account": "Delete Account",
  "edit_profile": "Edit profile",
  "wallet": "Wallet",
  "cancel": "Cancel",
  "settings": "Settings",
  "support_and_info": "Support & Information",
  "more": "More",
  "my_profile": "My Profile",
  "order_details": "Order Details",
  "order_date_time": "Order Date/Time",
  "order_id": "Order ID",
  "payment_method": "Payment Method",
  "type": "Type",
  "status": "Status",
  "from_date": "From Date",
  "to_date": "To Date",
  "search": "Search",
  "search_all_orders": "Search all orders",
  "order_filter": "Order Filter",
  "clear_filters": "Clear Filters",
  "apply": "Apply",
  "simple": "Simple",
  "digital": "Digital",
  "order_status": "Order Status",
  "update": "Update",
  "shipping_details": "Shipping Details",
  "delivery_preference": "Delivery Preference",
  "price_details": "Price Details",
  "phone_number": "Phone Number",
  "delivery_instruction": "Delivery Instruction",
  "subtotal": "Subtotal",
  "tax": "Tax",
  "shipping_charges": "Shipping Charges",
  "wallet_balance": "Wallet Balance",
  "discount_amount": "Discount Amount",
  "promo_code_discount": "Promo Code Discount",
  "payable_total": "Payable Total",
  "total_amount": "Total Amount",
  "order_created": "Order created",
  "payment_mode": "Payment Mode",
  "return_pending": "Return Pending",
  "return_approved": "Return Approved",
  "return_decline": "Return Decline",
  "return_pickedup": "Return pickedup",
  "all": "All",
  "wallet_withdraw": "Wallet Withdraw",
  "withdraw": "Withdraw",
  "pending": "Pending",
  "approved": "Approved",
  "rejected": "Rejected",
  "current_balance": "Current Balance",
  "withdraw_money": "Withdraw Money",
  "wallet_transaction": "Wallet Transaction",
  "account_number": "Account Number",
  "name": "Name",
  "bank_details": "Bank Details",
  "success": "Success",
  "message": "Message",
  "date": "Date",
  "amount": "Amount",
  "collected": "Collected",
  "cash_collection": "Cash Collection",
  "rider_cash": "Rider Cash",
  "email": "Email",
  "address": "Address",
  "driving_licence_front_image": "Driving Licence Front Image",
  "driving_licence_back_image": "Driving Licence Back Image",
  "recommended_size_180_x_200_pixels": "(Recommended Size : 180 x 200 pixels)",
  "confirm_password": "Confirm Password",
  "upload_driving_licence": "Upload Driving Licence",
  "upload_profile_image": "Upload Profile Image",
  "serviceable_zipcodes": "Serviceable Zipcodes",
  "try_again": "Try Again",
  "serviceable_cities": "Serviceable Cities",
  "bonus_type": "Bonus Type",
  "bonus_amount": "Bonus Amount",
  "bonus_percentage": "Bonus Percentage",
  "percentage_per_order_item": "Percentage Per Order Item",
  "fixed_amount_per_order_item": "Fixed Amount Per Order Item",
  "welcome": "Welcome",
  "new": "New",
  "earlier": "Earlier",
  "balance": "Balance",
  "total_balance": "Total Balance",
  "total_bonus": "Total Bonus",
  "total_orders": "Total Orders",
  "bonus": "Bonus",
  "recent_orders": "Recent Orders",
  "no_orders_assigned_yet": "No orders assigned yet!",
  "don_t_worry_new_deliveries_will_show_up_here_soon_stay_ready":
      "Don't worry, new deliveries will show up here soon. Stay ready!",
  "select_status": "Select Status",
  "seller": "Seller",
  "click_to_open_file": "Click to open file",
  "direction": "Direction",
  "storage_permission_not_granted": "Storage permission not granted",
  "are_you_sure_you_want_to_turn_off_notifications":
      "Are you sure you want to turn off notifications?",
  "select_zones": "Select Zones",
  "please_enter_all_required_fields": "Please enter all required fields",
  "enter_otp": "Enter OTP",
  "tax_already_included": "Tax Already Included",
  "modifications_are_not_allowed_in_demo_app":
      "Modifications are not allowed in demo app",
  "open_link": "Open link",
  "unauthenticated_please_login_again": "Unauthenticated. Please login again."
};
