import 'dart:io';

import 'package:value_market_customer/core/configs/appConfig.dart';

Map<String, String> defaultLanguageTranslatedValues = {
  "default_error_message": "Something went wrong. Please try again later!",
  "internal_server_error_message":
      "Internal Server Error. Please try again later!",
  "empty_value_error_message": "Please enter some value",
  "verification_error_message": "Verification failed. Please try again!",
  "invalid_email_error_message":
      "Email adddress is invalid. Pelase enter valid format",
  "invalid_name_error_message": "Name is invalid. Please enter valid format",
  "invalid_mobile_error_msg": "Please enter valid mobile number",
  "invalid_otp_message_error_msg": "OTP is incorrect",
  "password_mismatch_message":
      'Confirm Password do not match with new password',
  "account_exist_google_error_message":
      'The account already exists with a different credential.',
  "error_in_credentials_error_message":
      'Error occurred while accessing credentials. Try again.',
  "error_in_siginn_google_error_message":
      'Error occurred using Google Sign-In. Try again.',
  "deactivated_error_message": 'You are deactivated. You can\'t login to app.',
  "data_not_available": "Data not available",
  "incorrect_length_of_password_error":
      "The password must be at least 6 characters.",
  "apple_login_cancelled_error_msg": "User has cancelled login process",
  "please_login": "Please login to continue",
  "require_recent_login_error_message":
      'The user must relogin before this operation can be executed.\nThen you can initiate delete procedure.',
  "require_recent_login": 'Require Recent Login',
  "app_under_maintenance":
      "Sorry for the inconvenience. This app is under maintenance.",
  "retry": 'Retry',
  "skip": "Skip",
  "shop_for": "Shop For",
  "sign_in": "Sign In",
  "sign_up": "Sign Up",
  "login": "Login",
  "by_continuing_you_agree_to_our":
      "By Signing Up /Logging in, you agree to our ",
  "terms_of_services": "Terms of Services",
  "and": "and",
  "or_signup_with": "Or Signup With",
  "or_login_with": "Or Login With",
  "sign_up_with_google": Platform.isAndroid ? "Sign Up with Google" : "Google",
  "sign_in_with_google": Platform.isAndroid ? "Sign In with Google" : "Google",
  "sign_up_with_apple": "Apple",
  "sign_in_with_apple": "Apple",
  "hi_welcome_back": "Hi, Welcome Back!",
  "please_enter_login_details":
      "Please enter your login details below to start using app.",
  "mobile_number": "Mobile Number",
  "we_will_send_verification_code_to":
      "We will send a password reset link to your registered email ID.",
  "we_will_send_verification_code_to_number":
      "We will send a verification code to this number.",
  "dont_have_account": "Don't have an account?",
  "password": "Password",
  "username": "Username",
  "name": "Name",
  "email": "Email",
  "referral_code": "Referral Code (optional)",
  "phone_number": "Phone Number",
  "create_new_account": "Create a new account",
  "create_account": "Create Account",
  "create_new_account_desc":
      "Please put your information below to create a new account for using app.",
  "please_accept_terms_and_condition_and_privacy_policy":
      "Please accept Terms & condition and Privacy policy",
  "forgot_password": "Forgot Password?",
  "forgot_password_title": "Forgot Password",
  "get_password": "Get Password",
  "enter_verification_code": "Enter Verification Code",
  "we_have_sent_verification_code_to": "We have sent a verification code to",
  "verify_otp": "Verify OTP",
  "send_o_t_p": "Send OTP",
  "didnt_get_otp": "Didn't get the code?",
  "resend_otp": "Resend OTP",
  "reset_password": "Reset password",
  "new_password": "New password",
  "confirm_new_password": "Confirm New Password",
  "please_typesomething": "Please Type something you'll remember",
  "no_internet": "No Internet Connection. Please try again",
  "incorrect_o_t_p": "Incorrect otp",
  "hinted_search_text": "Hinted search text",
  "next": "Next",
  "back": "Back",
  "register": "Register",
  "confirm_password": "Confirm Password",
  "address": "Address",
  "home": "Home",
  "category": "Category",
  "explore": "Explore",
  "cart": "Cart",
  "user": "User",
  "add_delivery_loc": "Add Delivery Location",
  "select_delivery_loc": "Select Delivery Location",
  "select_delivery_loc_desc":
      "Set your delivery location to see products availability",
  "type_delivery_pincode": "Type Delivery Pincode",
  "select_store": "Select Store",
  "shop_by_category": "Shop By Category",
  "see_all": "See All",
  "no": "No",
  "yes": "Yes",
  "terms_and_conditions": "Terms & Conditions",
  "privacy_policy": "Privacy Policy",
  "shipping_policy": "Shipping Policy",
  "return_policy": "Return and Refund Policy",
  "are_you_sure": "Are you sure?",
  "are_you_sure_to_exit_app": "Are you sure you want to exit the app?",
  "exit": "Exit",
  "submit": "Submit",
  "featured_sellers": "Featured Sellers",
  "featured_sellers_desc": "Shop from our top-rated sellers",
  "most_selling_products": "Most Selling Products",
  "see_collection": "SEE COLLECTION",
  "best_sellers_title": "Shop Our Supreme Best Sellers",
  "best_sellers_desc": "Find Your Favorites - Top Products Await",
  "brands": "Brands",
  "view_all_combos": "View All Combos",
  "all_products": "All Products",
  "combo_products": "Combo Products",
  "combo": "Combo",
  "min_price_should_be_greater_than": "Min price should be greater than",
  "max_price_should_be_less_than": "Max price should be less than",
  "inclusive_of_all_taxes": "Inclusive of all taxes",
  "all_sellers": "All Sellers",
  "sort": "Sort",
  "filter": "Filter",
  "popularity": "Popularity",
  "price_low_to_high": "Price : Low to High",
  "price_high_to_low": "Price : High to Low",
  "new_arrivals": "New Arrivals",
  "top_rated_product": "Top Rated Product",
  "ratings": "Ratings",
  "close": "Close",
  "price_range": "Price Range",
  "min": "Min",
  "max": "Max",
  "or_more": "or more",
  "and_above": "& above",
  "sort_by": "Sort By",
  "out_of_stock": "Out Of Stock",
  "view_store": "View Store",
  "view_comments": "View comments",
  "products": "Products",
  "add": "Add",
  "special_price": "Special Price",
  "price": "Price",
  "weight": "Weight (kg)",
  "height": "Height (cms)",
  "breadth": "Breadth (cms)",
  "length": "Length (cms)",
  "brand": "Brand",
  "discount": "Discount",
  "clear_all": "Clear All",
  "clear_filters": "Clear Filters",
  "apply": "Apply",
  "top_rated": "Top Rated",
  "newest_first": "Newest First",
  "oldest_first": "Oldest First",
  "my_profile": "My Profile",
  "my_order": "My Order",
  "my_orders": "My Orders",
  "coupons": "Coupons",
  "profile": "Profile",
  "account": "Account",
  "settings": "Settings",
  "support_and_info": "Support & Information",
  "more": "More",
  "refer_and_earn": "Refer & Earn",
  "manage_pickup_loc": "Manage Pickup Location",
  "stock_management": "Stock Management",
  "sales_report": "Sales Report",
  "change_language": "Change Language",
  "change_theme": "Change Theme",
  "faq": "FAQ's",
  "contact_us": "Contact Us",
  "customer_support": "Customer Support",
  "about_us": "About Us",
  "terms_and_policy": "Terms and Policies",
  "rate_us": "Rate Us",
  "share_app": "Share App",
  "logout": "Logout",
  "delete_account": "Delete Account",
  "edit_profile": "Edit profile",
  "wallet": "Wallet",
  "transaction": "Transaction",
  "chat": "Chat",
  "add_product": "Add Product",
  "change_password": "Change Password",
  "notification_pref": "Notifications Preference",
  "current_password": "Current Password",
  "enter_your_current_password": "Enter your current password",
  "enter_your_new_password": "Enter your new password",
  "are_you_sure_you_want_to_logout": "Are you sure you want to logout?",
  "yes_logout": "Yes, Logout",
  "stay_logged_in": "Stay logged in",
  "are_you_sure_you_want_to_delete_account":
      "Are you sure you want to delete your account?",
  "yes_delete": "Yes, Delete",
  "keep_account": "Keep account",
  "notifications": "Notifications",
  "push_notifications": "Push Notifications",
  "promotional_emails": "Promotional Emails",
  "promotional_s_m_s": "Promotional SMS",
  "save_password": "Save Password",
  "delete_my_account": "Delete My Account Now",
  "back_to_profile": "Back to Profile",
  "deleteAccntWarning1":
      "Please note that this action is irreversible and will permanently remove your account information.",
  "deleteAccntWarning2":
      "By deleting your account, you'll lose access to your order history and personalized settings. If you have any queries, don't hesitate to contact us.",
  "current_balance": "Current Balance",
  "withdraw_money": "Withdraw Money",
  "wallet_transaction": "Wallet Transaction",
  "wallet_withdraw": "Wallet Withdraw",
  "message": "Message",
  "date": "Date",
  "type": "Type",
  "amount": "Amount",
  "add_money": "Add Money",
  "fail": "Fail",
  "success": "Success",
  "pending": "Pending",
  "approved": "Approved",
  "rejected": "Rejected",
  "your_referral_code": "Your referral code",
  "refer_and_earn_desc":
      "Invite your friends to join and get the reward as soon as your friend first order Placed.",
  "noefer_and_earn": "No Referral Code",
  "share": "Share",
  "save": "Save",
  "payment_method": "Payment Method",
  "payment_mode": "Payment Mode",
  "search_all_orders": "Search all orders",
  "search_category": "Search Category",
  "no_sub_categories_found": "No Sub Categories Found",
  "go_to_products": "Explore Products",
  "status": "Status",
  "time": "Time",
  "all": "All",
  "anytime": "Anytime",
  "last30Days": "Last 30 days",
  "last_six_months": "Last 6 months",
  "last_year": "Last year",
  "received": "Received",
  "processed": "Processed",
  "shipped": "Shipped",
  "delivered": "Delivered",
  "cancelled": "Cancelled",
  "returned": "Returned",
  "return_request_pending": "Return Pending",
  "return_request_approved": "Return Approved",
  "return_request_decline": "Return Decline",
  "on_the_way": "On The Way",
  "my_address": "My Address",
  "add_new_address": "Add New Address",
  "my_address_details": "My Address Details",
  "state": "State",
  "select_city": "Select City",
  "select_pincode": "Select Pincode",
  "area_name": "Area/Apartment Name",
  "pincode": "Pincode",
  "latitude": "Latitude",
  "longitude": "Longitude",
  "save_this_address_as": "Save This Address As",
  "office": "Office",
  "other": "Other",
  "save_address_as_default": "Save address as default",
  "save_address": "Save Address",
  "edit_address": "Edit Address",
  "delete": "Delete",
  "search_city": "Search City",
  "search_pincode": "Search Pincode",
  "please_select_city": "Please select a city first",
  "choose_location": "Choose Location",
  "update_location": "Update Location",
  "pick_up": "Pick Up",
  "no_addresses": "No Addresses",
  "app_language": "App Language",
  "redeem": "Redeem",
  "expires_on": "Expires On",
  "order_details": "Order Details",
  "delivery_address": "Delivery  Address",
  "price_details": "Price Details",
  "seller_details": "Seller Details",
  "shipment_details": "Shipment Details",
  "item_total": "Item Total",
  "coupon_discount": "Coupon Discount",
  "delivery_charges": "Delivery Charges",
  "total_amount": "Total Amount",
  "order_date_time": "Order Date/Time",
  "order_i_d": "Order ID",
  "order_total": "Order Total",
  "download_invoice": "Download Invoice",
  "totalpayable": "Total Payable",
  "wallet_balance": "Wallet Balance",
  "more_product_in_this_order": "More Product in this Order",
  "cancel": "Cancel",
  "wishlist": "Wishlist",
  "add_to_cart": "Add to Cart",
  "go_to_cart": "Go to Cart",
  "no_favorites": "No favorites yet!",
  "order_confirmed": 'Order Confirmed',
  "out_for_delivery": 'Out For Delivery',
  "please_check_your_mail": "Please check your Mail for instruction",
  "send": 'Send',
  "bank_details": 'Bank Details',
  "withdrawal_amount": 'Withdrawal Amount',
  "account_number": "Account Number",
  "ifsc_code": "IFSC Code",
  "payment_methods": "Payment Methods",
  "paypal": "Paypal",
  "phonepe": "Phonepe",
  "razorpay": "Razorpay",
  "paystack": "Paystack",
  "stripe": "Stripe",
  "cash_on_delivery": "Cash On Delivery",
  "ask_query": "Ask Query",
  "send_query": "Send Query",
  "select_your_query": "Select Your Query",
  "select_issue_type": "Select issue Type",
  "pls_select_issue_type": "Please select issue type",
  "select_issue_category": "Select issue Category",
  "opened": "Opened",
  "resolved": "Resolved",
  "closed": "Closed",
  "reopened": "Reopened",
  "subject": "Subject",
  "description": "Description",
  "edit": "Edit",
  "select_ticket_status": "Select Ticket Status",
  "please_select_ticket_status": "Please select ticket status",
  "search_seller": "Search Seller",
  "seller": "Seller",
  "sellers": "Sellers",
  "add_zipcode_manually":
      "Didn't find your pincode in the list ? Enter your pincode in above textbox and tap 'Add' to use that pincode manually.",
  "cancel_product_warning": "Are you sure you want to cancel this product?",
  "return_product_warning": "Are you sure you want to return this product?",
  "return_product_due_date":
      "We're sorry, but the return period for this item has passed and it is no longer eligible for return.",
  "return_product": "Return Product",
  "payment_back_warning": "Don't press back while doing payment!",
  "payment_exit_instruction": "Double tap back button to exit",
  "phone_pe_payment_success": "PhonePe Payment Successful.",
  "phone_pe_payment_failed": "PhonePe Payment Failed.",
  "transaction_successful": "Transaction Successful",
  "transaction_fail": "Transaction Failed",
  "download": "Download",
  "storage_permission_not_granted": "Storage permission not granted",
  "categories": "Categories",
  "invoice_downloaded": "Invoice downloaded successfully",
  "file_downloaded": "File downloaded successfully",
  "view": "View",
  "questions_and_answers": "Questions and Answers",
  "see_all_questions": "See all Questions",
  "ratings_and_reviews": "Ratings & Reviews",
  "all_offer_and_coupons": "All offers & Coupons",
  "enter_coupon_code": "Enter Coupon Code",
  "please_enter_coupon_code": "Please enter Coupon Code",
  "empty_cart_error_message":
      "Your cart is empty. Please add some product to cart and try again",
  "new": "New",
  "earlier": "Earlier",
  "products_details": "Product Details",
  "reviews": "Reviews",
  "country_of_origin": "Country of Origin",
  "ingredient_type": "Ingredient Type",
  "veg": "Vegetarian",
  "non_veg": "Non Veg",
  "compare_with_similar_items": "Compare with similar items",
  "images_uploaded_by_customers": "Images uploaded by customers",
  "customer_reviews": "Customer Reviews",
  "customer_photos": "Customer Photos",
  "similar_products": "Similar Products",
  "post_your_question": "Post Your Question",
  "write_question": "Write Question",
  "type_your_question": "Type Your Question",
  "excellent": "Excellent",
  "good": "Good",
  "average": "Average",
  "poor": "Poor",
  "all_reviews": "All Reviews",
  "filter_review": "Filter Review",
  "made_in": "Made In",
  "warranty": "Warranty",
  "guarantee": "Guarantee",
  "returnable": "Returnable",
  "cancellable": "Cancellable",
  "cancellable_till": "Cancellable Till",
  "max_days_to_return_item": "Max days to return item",
  "product_you_might_like": "Product You Might Like",
  "recent_searches": "Recent Searches",
  "most_searched": "Most Searched",
  "recently_viewed": "Recently Viewed",
  "clear": "Clear",
  "buy_now": "Buy Now",
  "check": "Check",
  "check_product_deliverability": "Check Product Deliverability",
  "see_offers": "See Offers",
  "change": "Change",
  "remove": "Remove",
  "save_for_later": "Save For Later",
  "remove_from_cart_title": "Move from cart?",
  "remove_from_cart_desc": "You can save Product and buy them later",
  "empty_cart":
      "Your cart is currently empty. Start adding your favorite items and they will appear here!",
  "add_from_favorites": "Add from favorites",
  "add_coupon_code": "Add Coupon Code",
  "place_order": "Place Order",
  "applied": "Applied",
  "you_saved": "You Saved",
  "with_this_coupon_code": "With This Coupon Code",
  "cashback_warning":
      "Cashback from this promo code will be added to your wallet after your order is successfully delivered.",
  "note": "Note",
  "tax": "Tax",
  "deliver_to_this_address": "Deliver To This Address",
  "add_delivery_instruction": "Add Delivery Instruction",
  "select_address": "Select Address",
  "select_payment": "Select Payment",
  "payment": "Payment",
  "continue": "Continue",
  "minOrderAmountWarning1":
      "Your cart total is below the minimum required amount ",
  "minOrderAmountWarning2": "Please add more items to proceed with checkout.",
  "available_balance": "Available balance",
  "product_type_mixing_warning":
      "You cannot add both physical and digital products to the cart.",
  "not_delierable_error_message": "is Not deliverable at Selected Address",
  "delivery_estimates": "Delivery Estimates",
  "estimated_delivery_by": "Estimated Delivery by",
  "net_amount": "Net Amount",
  "total": "Total",
  "item_added_cart_message": "Item successfully added to your cart.",
  "select_pack": "Select Pack",
  "confirm": "Confirm",
  "max_cart_limit_warning":
      "Maximum cart capacity reached. Please proceed to checkout or remove items before adding more.",
  "your_order_will_delivered_soon": "Your Order Will be delivered soon.",
  "track_your_order": "Track Your Order",
  "back_to_home": "Back to Home",
  "select_payment_method": "Please select a payment method",
  "seller_order_system_warning":
      "You can only place an order from one seller at a time. If you'd like to purchase from another seller, please complete or remove the items from your current cart first.",
  "max_quantity_reached":
      "Sorry, you've reached the maximum order quantity for this item.",
  "min_quantity_reached":
      "Sorry, the quantity cannot be reduced further. You've reached the minimum order limit for this item.",
  "stock_limit_reached":
      "Cannot add more of this product. Stock limit reached.",
  "change_address": "Change Address",
  "update": "Update",
  "force_update_title": "Update Required",
  "force_update_desc":
      "A new version of this app is available with important improvements and features. To continue using the app, please update to the latest version.",
  "write_message": "Write message",
  "customer_care": "Customer Care",
  "enter_email_for_checkout": "Please add email address for checkout",
  "enter_email": "Type your email address",
  "enter_email_desc":
      "Enter your email address on which you want your digital product to be delivered",
  "admin": "Admin",
  "login_to_add_to_cart":
      "Login Required. Please log in to add items to your cart.",
  "rate_the_product": "Rate the Product",
  "add_title": "Add Title",
  "write_title": "Write Title",
  "write_review": "Write a review",
  "add_review": "Add review",
  "submit_review": "Submit Review",
  "update_review": "Update Review",
  "share_image": "Share Image",
  "tax_already_included": "Tax Already Included",
  "withdraw": "Withdraw",
  "off_notification_warning":
      "Are you sure you want to turn off notifications from $appName?",
  "delete_acct_not_allowed_in_demo_app":
      "Demo app doesn't allow account deletion",
  "no_zipcode_found": 'No Zipcode Found for selected city',
  "select_address_warning": "Please select address",
  "enter_valid_amount": "Enter a valid amount",
  "attachment_is_required_for_this_product_when_you_place_an_order":
      "Attachment is required for this product when you place an order",
  "note_please_note_that_only_image_or_document_files_are_allowed_for_upload":
      "Note: Please note that only image or document files are allowed for upload.",
  "warning_attachment_required_for_some_of_the_products_but_not_provided":
      "Warning: Attachment required for some of the products, but not provided.",
  "please_select_either_payment_method_or_wallet_balance_to_continue":
      'Please select either Payment Method or Wallet Balance to continue',
  "delivery_charges_may_apply_as_per_your_address_preferences_you_will_see_final_amount_in_checkout_screen":
      "Delivery charges may apply as per your address preferences. You will see final amount in checkout screen.",
  "you_can_eiher_use_wallet_balance_or_payment_method_to_pay_for_your_order":
      "You can eiher use wallet balance or payment method to pay for your order",
  "proceed_to_checkout": "Proceed to checkout",
  "awaiting": "Awaiting",
  "best_seller": "BEST SELLER",
  "new_arrival": "NEW ARRIVAL",
  "check_out_this_amazing_product": "Check out this amazing product",
  "product_name": "Product Name",
  "share_this_seller_with_your_friends_and_family":
      "Share this seller with your friends and family",
  "open_link": "Open link",
  "are_you_sure_you_want_to_delete?": "Are you sure you want to delete?",
  "please_remove_out_of_stock_products_from_cart_or_add_them_in_saved_for_later_list_to_proceed_with_checkout":
      "Please Remove out of stock products from cart or add them in Save For Later list to proceed with checkout",
  "this_product_is_currently_out_of_stock":
      "This product is currently out of stock.",
  "by": "By",

  "payment_methods_are_not_available": "Payment methods are not available",
  "items_in_this_combo": "Items in this combo",
  "min_price_msg": "Min price should be greater than ",
  "max_price_msg": "Max price should be less than ",
  "wallet_balance_should_not_be_less_than_total_amount":
      "Wallet balance should not be less than total amount",
  "microphone_and_speech_permissions_denied":
      "Microphone and Speech permissions denied.",
  "microphone_permission_is_disabled_._please_enable_it_in_Settings":
      "Microphone permission is disabled. Please enable it in Settings.",

  //new
  "press_back_again_to_exit": "Press back again to Exit",
  "direct_bank_transfer": "Direct Bank Transfer",
  "Instructions_Make_your_payment_directly_into_our_account_Your_order_will_not_further_proceed_until_the_funds_have_cleared_in_our_account_You_have_to_send_your_payment_receipt_from_order_details_page_then_admin_will_verify_that":
      "Instructions! Make your payment directly into our account. Your order will not further proceed until the funds have cleared in our account.\nYou have to send your payment receipt from order details page then admin will verify that.",
  "account_details": "Account Details!",
  "account_name": "Account Name",
  "bank_name": "Bank Name",
  "bank_code": "Bank Code",
  "extra_details": "Extra Details!",
  "reset": "Reset",
  "upload": "Upload",
  "bank_payment_receipt": "Bank Payment Receipt",
  "choose_files": "Choose Files",
  "select_file_warning":
      "Please select one or more file for bank transfer proof",
  "uploaded_files": "Uploaded Files",
  "accepted": "Accepted",
  "upload_file": "Upload File",
  "return_pickedup": "Return pickedup",
  "unauthenticated_please_login_again": "Unauthenticated. Please login again."
};
